INPUT_LAYER_NEURONS = 5

HIDDEN_LAYER_MAX_DEPTH = 12
HIDDEN_LAYER_MAX_UNITS = 50
HIDDEN_LAYER_MIN_UNITS = 5
HIDDEN_LAYER_STEP_UNITS = 5
HIDDEN_LAYER_ACTIVATIONS = ['sigmoid', 'tanh', 'relu', 'elu']

DROPOUT_LAYER_MAX_RATE_PERCENT = 50
DROPOUT_LAYER_MIN_RATE_PERCENT = 10
DROPOUT_LAYER_STEP_RATE_PERCENT = 10

OUTPUT_LAYER_NEURONS = 1
OUTPUT_LAYER_ACTIVATION = 'sigmoid'

INPUT_OUTPUT_PROBABILITY = 0.1

HIDDEN_OUTPUT_PROBABILITY_START = 0.1
HIDDEN_OUTPUT_PROBABILITY_END = 0.6

DROPOUT_OUTPUT_PROBABILITY_START = 0.1
DROPOUT_OUTPUT_PROBABILITY_END = 0.6
